<?php

class EquipmentPower{
    
    public $power =  [
        "loy"=>[
            "boot"=>[
               [
                    "attack"=>1,
                    "def"=>1,
                    "vit"=>4,
                    "dam"=>0
               ]
            ],
            "shield"=>[
                [
                    "attack"=>1,
                    "def"=>2,
                    "vit"=>14,
                    "dam"=>0
                ]
            ],
            "armor"=>[
                [
                    "attack"=>0,
                    "def"=>1,
                    "vit"=>10,
                    "dam"=>1
                ]
            ],
            "helmet"=>[
                [
                    "attack"=>0,
                    "def"=>1,
                    "vit"=>13,
                    "dam"=>1
                ]
            ],
            "sword"=>[
                [
                   "attack"=>3,
                    "def"=>0,
                    "vit"=>0,
                    "dam"=>4
                ]
            ]
        ],
        "lion"=>[
            "boot"=>[
                [
                    "attack"=>4,
                    "def"=>4,
                    "vit"=>0,
                    "dam"=>4
                ]
            ],
            "shield"=>[
                [
                    "attack"=>0,
                    "def"=>16,
                    "vit"=>48,
                    "dam"=>0
                ]
            ],
            "armor"=>[
               [ 
                   "attack"=>0,
                "def"=>12,
                "vit"=>32,
                "dam"=>0
                   ]
            ],
            "helmet"=>[
                [
                    "attack"=>8,
                    "def"=>0,
                    "vit"=>48,
                    "dam"=>4
                ]
            ],
            "sword"=>[
                [
                    "attack"=>32,
                    "def"=>0,
                    "vit"=>0,
                    "dam"=>16
                ]
            ]
        ],
        "fearless"=>[
            "boot"=>[
                [
                    "vit"=>0,
                    "attack"=>8,
                    "defence"=>8,
                    "damage"=>8
                ]
            ],
            "shield"=>[
                [
                    "vit"=>90,
                    "attack"=>0,
                    "defence"=>30,
                    "damage"=>0
                ]
            ],
            "armor"=>[
                [
                    "vit"=>60,
                    "attack"=>0,
                    "defence"=>20,
                    "damage"=>0
                ]
            ],
            "helmet"=>[
                [
                    "vit"=>60,
                    "attack"=>10,
                    "defence"=>0,
                    "damage"=>5
                ]
            ],
            "sword"=>[
                [
                    "vit"=>0,
                    "attack"=>60,
                    "defence"=>0,
                    "damage"=>30
                ]
            ]
        ],
    ];
    
}
